pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir ("app") {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir ("app") {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'app/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './app/jenkins/scripts/deliver.sh'
            }
        }
    }
}
